jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - script: curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --version 2.1.202 && export PATH="$HOME/.dotnet:$PATH"
  - script: dotnet --info
- job: macOS
  pool:
    vmImage: 'xcode9-macos10.13'
  steps:
  - script: dotnet --info
- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - script: dotnet --info
