name: 'Docker Publish'
description: 'Docker Publish Images'
inputs:
  arch:
    description: 'Docker architecture'
    required: true
  docker_distro:
    description: 'Linux Distro'
    required: true
  dotnet_version:
    description: '.net version'
    required: true
  docker_registry_username:
    description: 'DockerHub Registry Username'
    required: true
  docker_registry_password:
    description: 'DockerHub Registry Password'
    required: true
  github_registry_username:
    description: 'GitHub Registry Username'
    required: true
  github_registry_password:
    description: 'GitHub Registry Password'
    required: true
    
runs:
  using: 'composite'
  steps:
  -
    name: Login to DockerHub
    uses: docker/login-action@v3
    with:
      username: ${{ inputs.docker_registry_username }}
      password: ${{ inputs.docker_registry_password }}
  -
    name: '[Docker Publish] DockerHub'
    uses: nick-fields/retry@v3
    with:
      timeout_seconds: 15
      max_attempts: 3
      retry_on: error
      shell: pwsh
      command: >-
        dotnet run/docker.dll
              --target=DockerPublish --arch=${{ inputs.arch }} --dotnet_version=${{ inputs.dotnet_version }}
              --docker_distro=${{ inputs.docker_distro }} --docker_registry dockerhub --verbosity=diagnostic
  -
    name: Login to GitHub
    uses: docker/login-action@v3
    with:
      registry: ghcr.io
      username: ${{ inputs.github_registry_username }}
      password: ${{ inputs.github_registry_password }}
  -
    name: '[Docker Publish] GitHub'
    shell: pwsh
    run: >-
        dotnet run/docker.dll `
              --target=DockerPublish --arch=${{ inputs.arch }} --dotnet_version=${{ inputs.dotnet_version }} `
              --docker_distro=${{ inputs.docker_distro }} --docker_registry github --verbosity=diagnostic
