on:
  workflow_call:

env:
  DOTNET_INSTALL_DIR: "./.dotnet"
  DOTNET_ROLL_FORWARD: "Major"
  
jobs:
  artifacts:
    name: ${{ matrix.package }}
    runs-on: windows-2025
    strategy:
      fail-fast: false
      matrix:
        package: [ Executable, MsBuildFull ]

    steps:
    -
      name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    -
      name: Restore State
      uses: ./.github/actions/cache-restore
    -
      uses: actions/download-artifact@v5
      name: Download nuget packages
      with:
        name: nuget
        path: ${{ github.workspace }}/artifacts/packages/nuget
    -
      name: '[Test Artifacts]'
      shell: pwsh
      run: dotnet run/artifacts.dll --target=Artifacts${{ matrix.package }}Test
