on:
  workflow_call:

env:
  DOTNET_INSTALL_DIR: "./.dotnet"
  DOTNET_ROLL_FORWARD: "Major"
  
jobs:
  build:
    name: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2025, ubuntu-24.04, macos-15]

    runs-on: ${{ matrix.os }}
    steps:
    -
      name: Checkout
      uses: actions/checkout@v5
      with:
        fetch-depth: 0
    -
      name: Restore State
      uses: ./.github/actions/cache-restore
    -
      name: '[Build]'
      shell: pwsh
      run: dotnet run/build.dll --target=Package
    -
      name: 'Upload nuget packages'
      uses: actions/upload-artifact@v5
      if: matrix.os == 'windows-2025'
      with:
        name: nuget
        path: ${{ github.workspace }}/artifacts/packages/nuget
    -
      name: 'Upload native packages'
      uses: actions/upload-artifact@v5
      if: matrix.os == 'windows-2025'
      with:
        name: native-${{ runner.os }}
        path: ${{ github.workspace }}/artifacts/packages/native/*.zip
    -
      name: 'Upload native packages'
      uses: actions/upload-artifact@v5
      if: matrix.os != 'windows-2025'
      with:
        name: native-${{ runner.os }}
        path: ${{ github.workspace }}/artifacts/packages/native/*.tar.gz
