on:
  workflow_call:

env:
  DOTNET_INSTALL_DIR: "./.dotnet"

jobs:
  manifest:
    name: ${{ matrix.distro }} - net${{ matrix.targetFramework }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        distro: [ alpine.3.16, alpine.3.17, centos.7, centos.stream.8, fedora.36, debian.11, ubuntu.20.04, ubuntu.22.04 ]
        targetFramework: [ '7.0', '6.0' ]

    steps:
    -
      name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    -
      name: Restore State
      uses: ./.github/actions/artifacts-restore
    -
      name: Docker Manifests
      if: success() && github.event_name != 'pull_request' && github.repository_owner == 'GitTools' && github.ref_name == 'main'
      uses: ./.github/actions/docker-manifests
      with:
        distro: ${{ matrix.distro }}
        targetFramework: ${{ matrix.targetFramework }}
        docker_registry_username: ${{ secrets.DOCKER_USERNAME }}
        docker_registry_password: ${{ secrets.DOCKER_PASSWORD }}
        github_registry_username: ${{ github.repository_owner }}
        github_registry_password: ${{ secrets.DOCKER_GITHUB_TOKEN }}
