name: Code Format
on:
  push:
    branches:
    - main
    - 'fix/*'
    - 'feature/*'
    - 'poc/*'
    - 'support/*'
    paths:
    - '**'
    - '!docs/**'
    - '!.github/**'
    - .github/workflows/format.yml

  pull_request:
    branches:
    - main
    - 'support/*'
    paths:
    - '**'
    - '!docs/**'
    - '!.github/**'
    - .github/workflows/format.yml

permissions:
  contents: read

env:
  DOTNET_ROLL_FORWARD: "Major"
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: 1

jobs:
  format:
    runs-on: ubuntu-24.04
    name: DotNet Format
    steps:
      -
        name: Checkout
        uses: actions/checkout@v5
      -
        name: Setup .NET SDK
        uses: actions/setup-dotnet@v5
        with:
          global-json-file: global.json
      -
        name: Run Format 'ci' solution
        run: dotnet format ./build/ --verify-no-changes
      -
        name: Run Format 'GitVersion' solution
        run: dotnet format ./src/ --exclude **/AddFormats/ --verify-no-changes
