name: Homebrew

on:
  workflow_dispatch:
  repository_dispatch:
    types: [ publish-release ]
permissions:
  contents: read

jobs:
  homebrew:
    permissions:
      contents: none
    name: Bump Homebrew formula
    runs-on: macos-latest
    steps:
    - name: '[Release]'
      shell: pwsh
      run: echo "Release" ${{ github.event.client_payload.ref }}
#    - uses: dawidd6/action-homebrew-bump-formula@v3
#      with:
#        # GitHub token, required, not the default one
#        token: ${{ secrets.RELEASE_GITHUB_TOKEN }}
#        # Formula name, required
#        formula: gitversion
#        tag: ${{ github.event.client_payload.ref }}
