name: Build (new-cli)
on:
  push:
    branches:
    - main
    - 'fix/*'
    - 'feature/*'
    - 'poc/*'
    - 'support/*'
    paths:
    - '**'
    - '!docs/**'
    - '!.github/**'
    - .github/workflows/new-cli.yml

  pull_request:
    branches:
    - main
    - 'support/*'
    paths:
    - '**'
    - '!docs/**'
    - '!.github/**'
    - .github/workflows/new-cli.yml

permissions:
  contents: read

env:
  DOTNET_ROLL_FORWARD: "Major"
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: 1

jobs:
  format:
    runs-on: ubuntu-24.04
    name: Build & Test (new-cli)
    steps:
      -
        name: Checkout
        uses: actions/checkout@v5
      -
        name: Setup .NET SDK
        uses: actions/setup-dotnet@v5
        with:
          global-json-file: global.json
      -
        name: Build 'new-cli' solution
        run: dotnet build ./new-cli
      -
        name: Run Format 'new-cli' solution
        run: dotnet format ./new-cli --exclude ~/.nuget/packages --verify-no-changes
      -
        name: Test 'new-cli' solution
        run: dotnet test ./new-cli --no-build --verbosity normal
